# Model development

<!--
Sections from JK's MILP paper

# Model structure, formulation, and implementation

In our model, the urban region under study is

- Zones/demands/imports/exports
- Resources (demands)
- Conversion technologies (STN)
- RTN
- Interzonal connections
- Storage

# Mathematical formulation

- Key equation

## Imports and exports
## Resource conversion technologies
### Domestic technologies
### Part-Load operation
### Further extensions
## Units of measurement
## Transport technologies
## Storage technologies
### Detailed storage constraints
### Aggregate storage constraints
## Footprint constraint
## Performance metrics and objective function

# Implementation

- Ontology database
- GAMS
- Java app
-->

<!--
- [TODO: ref metric paper] showed that so-called 'grey-box' metrics (i.e. exergy-based and ENA-based) provide particularly helpful insights on urban resource efficiency.
	- Background section on precedent modelling: justify chosen metrics (e.g. exergy) with respect to Ravalde and Keirstead (2015), and justify omission of cost (one reason, is that our data included future technologies, i.e. as yet uncosted. Futhermore, 'costable' processes still vary around the world, due to exchange rates and differences in purchasing power, and furthermore, will change as a f(time)).
-->

Our model will consider a city as divided into a number of zones, for which can be specified demands for resource management, and which can contain the processes which convert resources. These zones also possess connections to other zones for resource transportation, and to outside the city for importing and exporting. To this end, our models will be based on the model by @Keirstead2013a which we introduced earlier as a high-level MILP model to plan urban energy resource systems.

To model the processes which convert resources, @Keirstead2013a looks to the engineering State-Task Network model of @Kondili1993, in which processes ('tasks') convert materials from one 'state' to another. Keirstead's model applies the same principles to urban energy systems in a so-called Resource-Technology Network (RTN), developing a model which chooses the mix of processes that uses available resources to meet demand for heat and electricity. While @Keirstead's model is categorised as having no system integration, the State-Task network representation is highly generalised (i.e. all conversion processes are represented by the same type of equation), thus the formulation can be easily extended to consider resources and processes from multiple sectors.

Like Keirstead's model, processes are separated into conversion processes (such as a wastewater treatment plant) and transport processes (such as a pipeline). The transport processes will connect the different zones into which an urban area is divided, allowing resources to be transported to and from different parts of the city. The main equation is a resource balance,

\begin{align}
I_{rzt} + \sum_p^P G^{(qty)}_{przt} + \sum_{\tau} V^{(qty)}_{rzt\tau} &= D^{(qty)}_{rzt} + E_{rzt},
\label{eq:bal_qty}
\end{align}

which specifies the amount of a particular resource $r$ at any given time $t$ in zone $z$. The demand $D^{(qty)}$ parameter is specified by the user, and the model will choose the resource quantity imported into the city $I$, exported from the city $E$, generated by conversion processes $G$, and net inflow from other zones $V$ (referred to as 'variables'). Like Keirstead's model, the resources are expressed in terms of quantities (such as MW of electricity or kg/s of solid waste), which in our equations is denoted by the $^{(qty)}$ superscript. However, here we evolve Keirstead's formulation, by defining resource flows in terms of their *quality*, such that a resource can be attributed with both an energy and a mass. This is useful as we consider interaction between different sectors. Consider a body of water: this can supply (for example) both cooling for industrial processes, and hydroelectric electricity -- in our model we would need to know both its mass, and its energy head due to elevation. Thus the formulation specifies an equation analogous to \eqref{eq:bal_qty} which defines flows in terms of their quality (using the $^{(qual)}$ superscript notation):

\begin{align}
X_{rq} I_{rzt} + \sum_p^P G^{(qual)}_{prqzt} + \sum_{\tau}^T V^{(qual)}_{\tau rqzt} &= D^{(qual)}_{rqzt} + X_{rq} E_{rzt} \qquad \forall q,
\label{eq:bal_qual}
\end{align}

This introduces the quality index $q$, and the parameter $X$ which defines a resource's quality[^qual-param] which is a multiplier of any resource quantity value, such that it separates a quantity into its qualities.

[^qual-param]: For example, 1 kg of static water at a 10 m elevation would have an energy head of 98.1 J. Thus $X_{rq}$ would be defined as $X_{\mbox{water, mass}} = 1$, $X_{\mbox{water, energy}} = 98.1$.

The variable $G$ denotes the net quality of resource produced by a conversion process in a zone at a particular time. Conversion processes are modelled as black boxes with resource inputs and outputs, defined by the coefficients $k^{proc}_{prq}$:

\begin{align}
G^{(qual)}_{prqzt} &= k_{prq} F_p,
\label{eq:conv_qual}
\end{align}

The variable $F_p$ defines the operation rate of a process $p$ which can run between a range of values (e.g. a power plant's maximum operating capacity). Using the $X_{rq}$ parameter, we can formulate the quantity version of \eqref{eq:conv_qual}:

\begin{align}
X_{rq}G^{(qty)}_{przt} &= k_{prq} F_{pzt},
\label{eq:conv_qty}
\end{align}

<!--
This equation only needs to be applied in the case where a process $p$ produces or consumes resource $r$ with qualities $q$, hence the condition based on the $\delta_{prq}$.
-->
Transport processes are defined similarly to conversion processes, using coefficients to represent the relative quantities of resources involved in the transfer from one zone to another, to calculate the variable $V$ for each zone, as the net inflow of a resource ($\mbox{summed inflow from all other zones} - \mbox{summed outflow to all other zones}$):

\begin{align}
V^{(qual)}_{\tau rqzt} = &\sum_{z'} (k^{\alpha}_{\tau rq} + k^{\beta}_{\tau rq} l_{zz'}) F^{transp}_{\tau zz't} + \\
+ &\sum_{z'} (k^{\alpha'}_{\tau rq} + k^{\beta'}_{\tau rq} l_{z'z}) F^{transp}_{\tau z'zt}
\label{eq:transp_qual}
\end{align}

Coefficients and process rates are defined for transport technology $\tau$, both for the zone of origin $z$, and the zone of destination $z'$ (where the $'$ notation indicates the destination zone). Furthermore, the quantity of input resources can be defined by the linear sum of two coefficients, denoted by $\alpha$ and $\beta$. For example to transport 1 kg of coal from $z$ to $z'$ (defined by $k_{\tau rq}^{\alpha}=-1$, $k_{\tau rq}^{\alpha'}=1$) will require a quantity of petrol dependent on the distance between the zones $l_{zz'}$, thus defined by $k_{\tau rq}^{\beta}$ and $k_{\tau rq}^{\beta'}$. In the case where transport losses occur (such as electricity transported via a cable), $k^{\alpha}_{\tau rq} > k^{\alpha'}_{\tau rq}$. To calculate the quantity flows, we once again use the $X_{rq}$ parameter:

\begin{align}
X_{rq}V^{(qty)}_{\tau rzt} = &\sum_{z'} (k^{\alpha}_{\tau rq} + k^{\beta}_{\tau rq} l_{zz'}) F^{transp}_{\tau zz't} + \\
+ &\sum_{z'} (k^{\alpha'}_{\tau rq} + k^{\beta'}_{\tau rq} l_{z'z}) F^{transp}_{\tau z'zt}
\label{eq:transp_qty}
\end{align}

Finally, the model will minimise some objective, for example, the cost of resource imports:

\begin{align}
\min\left\{\sum_{rzt} \mbox{cost}_r I_{rzt}\right\}
\label{eq:ob}
\end{align}

Equations \eqref{eq:bal_qty}--\eqref{eq:ob} form the programme's main constraints. For a full description, see Appendix [TODO: cross-ref to appropriate appendix] which lists other constraints (such as upper limits imposed on resource imports). The formulation includes continuous variables (such as resource quantities and process rates), integer variables (the number of conversion processes in a zone), and binary variables (for the existence of a transport process between two zones). All equations are linear, resulting in a mixed-integer linear programme (MILP).

The maximum rate at which a conversion process can operate is given as:

\begin{align}
F_{pz} \le N_{pz} F^{max}_p,
\end{align}

where the variable $N_{pz}$ is the number of process type $p$ in zone $z$, and the parameter $F^{max}_p$ is process $p$'s maximum operating rate.

The maximum rate between zones $z$ and $z'$ at which a transport process can operate is given as:

\begin{align}
F^{transp}_{\tau zz'} \le \delta^{transp}_{\tau zz'} F^{transp, max}_\tau,
\end{align}

where the integer variable $\delta_{\tau zz'}=1$ when transport process $\tau$ exists between zones $z$ and $z'$, and the parameter $F^{transp,max}_p$ is process $\tau$'s maximum operating rate (e.g. the maximum water flow rate of a pipe). Having defined the existence of a transport link between two zones, we assume that a link in one direction ($z \rightarrow z'$) necessarily defines a link in the opposite direction, thus:

\begin{align}
\delta^{transp}_{\tau zz'} = \delta^{transp}_{\tau z'z}
\end{align}

Further, we define a set $nb$ which specifies whether any two zones are neighbours. Only connections within this set can be linked by transport infrastructure. This not only models reality, but also reduces the model size:

\begin{align}
\delta^{transp}_{\tau zz'} = 0 \qquad \forall (z,z') \notin nb
\end{align}

The imports and export quantities must lie between $I^{min}$ and $I^{max}$ parameters, and thus can be expressed with the following constraint:

\begin{align}
\delta^{I}_{rz'} I^{min}_{rt} \leq I_{rzt} \leq \delta^{I}_{rz'} I^{max}_{rt}
\end{align}

where $\delta^I_{rz}$ is a binary variable which equals 1 if conversion process $r$ exists in zone $z$. This variable is itself subject to the constraint that only a $N^I_r$ zones can be used to import any given resource $r$:

\begin{align}
\sum_z \delta^{I}_{rz'} \leq N^I_r
\end{align}

Analogous constrains apply to exports:

\begin{align}
\delta^{E}_{rz'} E^{min}_{rt} &\leq E_{rzt} \leq \delta^{E}_{rz'} E^{max}_{rt} \\
\sum_z \delta^{E}_{rz'} &\leq N^E_r
\end{align}

Finally we consider possible objective functions, which could be a combination of costs ($C^*$) and environmental impacts. Resource costs could be defined, thus:

\begin{align}
C^R &= \sum_{rzt} c_r I_{rzt} \\
C^P &= \sum_{pz} c_p N_{pz} \\
C^{\tau} &= \sum_{\tau zz'} c_\tau \delta^{transp}_{\tau zz'} l_{zz'}
\end{align}

where the parameter $l_{zz'}$ defines the distance (length) between two zones. The costs above can be combined into a single objective function.

\begin{align}
C = \gamma^R C^R + \gamma^P C^P + \gamma^{\tau} C^{\tau}
\end{align}

where coefficients $\gamma^*$ could weight the component costs according to time span (e.g. a 20 year investment period), or their relative importance to a particular stakeholder.

Other types of objective function could include the carbon footprint $(CF)$ of an area, using the emissions factor of a resource $(ef)_r$:

\begin{align}
CF &= \sum_{rzt} (ef)_r I_{rzt}
\end{align}

More simple objective function might simply be to minimise the imports of a particular resource (e.g. water imports).

Objectives can be traded-off against each other, using so-called 'Pareto optimisation'. One equation is used as the objective function (for example cost), while another is defined as an inequality constraint (for example emissons):

\begin{align}
\sum_{rzt} (ef)_r I_{rzt} \leq lim
\end{align}

The user runs the model multiple times, changing the value of $lim$, such that one can plot a curve of emissions against cost.

As for implementation, our model requires both its equations to be encoded in a programming language which can be solved using MILP solvers (such as CPLEX or Gurobi), and the parameter data which defines the demands, process-behaviour and other constraints. These two elements are kept separate, making it convenient to generate different models for convenience. The data are stored in CSV and YAML text files, both of which are chosen for their human-readability and their ease of editing:

- CSV files specify any data with a spatial element, including the layout, the demands, import/export limits, etc. These have the advantage of being editable using spreadsheet software.
- YAML[^yaml] files define both resources and processes [TODO: further detail] in a human-readable format. This format allows data to be stored heirarchichally (i.e. nested like sub-items and sub-sub items in an itemized list).

[^yaml]: "YAML ain't a markup language". This format is more human-readable than other heirarchical data storage formats approaches such as XML and JSON.

To define a particular model instance, a configuration YAML specifies which YAML and CSV files), and R code then writes a GAMS script which combines the data with the code.

There is no doubt that modelling has helped planners and policy makers design systems to manage resources to optimal performance in cities. However, to date, energy, water and waste resources have been managed with their own separate modelling tools. But by neglecting the synergies between different resource types, these approaches limit the resource savings a city can make. Thus we have adapted @Keirstead2013a's urban energy systems model to introduce a new model which optimises an urban area's resource-technology management, by choosing an appropriate technology mix and a corresponding schedule of resource imports and exports. Using the database of @Ravalde2016, we have applied the model to a Chinese urban development case study, for [TODO: number] scenarios.

[TODO: discuss the middle of the system]
<!--
Despite a gallimaufry of urban metabolism models and resource optimisation models, there is still need for an integrated model, to meet ambitions for intersectoral urban synergies. We have begun this processes, developing @Keirstead2013a's model to create a generically defined [TODO: complete...]

In this paper, we have adapted the urban energy systems model of [TODO: cite Keirstead et al.] to formulate a new model which simultaneously optimises the management of energy, water and waste, to improve the metabolism of an area, and applied it to a new urban development in China, using data collected for @Ravalde2015b.
-->

- Assume documentation gives peak values
	- Assume peak values at all times?
	- Calculate daily averages based on peaks?
	- Compartmentalise into peaks and averages?

<!--
For the Appendix?

- Full mathematical formulation. I.e., in the main body, we only need to include the essential balance and process equations. Other constraints (e.g. limits on imports/exports can go in the Appendix).
- Demands
- Tabulate resource data (exergy, emissions, CF, WF Cost Revenue)
- Example black box process models
- Identify dummy processes (waste splitter, and waste generaliser, water splitter (recognising that higher quality waters can be used in lower quality applications)
- Example network configuration results
- Links to data, code and results on GitHub
- Summarised version of the demand data
- Link to GitHub/website of supplementary information
  	- CSV master table
	- R-script to produce data summaries, based on the master table's 'tidy' form.
	- Details on model formulation (comparison of performance, etc.)
	- Details on Shann Gu specific parameters (e.g. groundwater pumping, surface water availability, rainfall)
-->

