# Discussion and conclusions

\epigraph{``...when you close your eyes and imagine an epidemic spreading, or any other social dynamic, you are running some model or other. It is just an implicit model that you haven't written down...\par At least I can write mine down so that it can, in principle, be calibrated to data...\par The choice, then, is not whether to build models; it's whether to build explicit ones. In explicit models, assumptions are laid out in detail, so we can study exactly what they entail. On these assumptions, this sort of thing happens. When you alter the assumptions that is what happens. By writing explicit models, you let others replicate your results.''}{\citet{Epstein2008}}

<!--
In view of the growing urban populations
confronting environmental and economic challenges posed by the (otherwise desirable) phenomenon of urbanisation, 

To provide goods and services, cities are places of both great challenge and opportunities. In sustaining ever-growing populations in search of an improving quality of life, urban resource management needs are confronted by economic and environmental challenges. 

Our introduction showed that the energy, water and waste sectors interact, 
but in urban areas it is possible for these interactions to become synergies, by harnessing the co-location of infrastructure for 

Which gave rise to the research question

Reflecting upon the proximity of urban resource management processes in urban areas gave rise the idea of using the principles of industrial ecology at the urban level to improve UM as a whole. Looking to the ideas systems optimisation modelling in other sectors could proved a method to make this possible.
in adopting these principles of industrial ecology

The practical way forward for this:
- model - there complexity of identifying optimal process-mixes and operation schedules will increasingly require computational solutions.
- database

Optimisation modelling in general, and synergy-exploiting optimisation modelling is not far away from UM, and has been successfully applied in Industrial Ecology, especially as a means to integrate the operations of multiple facilities within Eco-Industrial Parks. This thesis has brought optimisation into the broader field


brought together urban metabolism, industrial ecology and optimisation modelling,

People have been using models to address complicated problems; to simplify complicated systems into ;


address the complexity of the problem with computational methods which use in effect quite easily understood equations, and datasets.

This work has been stated/formulated in terms of ‘urban metabolism’, since this is a research field which brings together various aspects of the study of urban areas in relation to their patterns of resource use, and thus provides an overarching framework, into which this work can speak and advance. 

This thesis has argued that to date, the UM has not yet sufficiently accounted for how an area's mix of resource management processes -- in this work, defined as the 'middle' of an urban system -- affects the aggregate exchanges of resources with the environment. 

This thesis has proposed that in view of the challenges posed by urbanisation, optimisation modelling should be adopted to help planners take advantage of intersectoral synergies. The model developed in this thesis achieved this by adding to the rliterature on resouce management, a generic MILP model at the urban scale which highly integrates the energy, water and waste management systems.

Related to this, this thesis has explored the best way to understand the efficiency of an area’s metabolism.

To that end, this thesis has added to the various extensions of UM's conceptual framework which began with @Wolman1965, and used this process-oriented model as the basis of a mathematical formulation of how resources are transferred between the derived demands of end-users, the network of processes which transport and convert resources, and area beyond the urban boundary. Using MILP methods, it is then possible to compute optimal 


However, a mere mathematical description of the middle of a system is not sufficient to explore these questions, and thus we assembled a database of over 300 processes which a city might use in its management of energy, water and waste, which provides data for the model.

## Summary
-->

Chapter \ref{sec:intro} highlighted both the socioeconomic importance of cities, and the challenge they face in managing their resources in an environmentally- and economically-sustainable way. One way for cities to address their challenges is to take advantage of their co-located infrastructure, by using the wastes and by-products of one process as the inputs to another, and thus responding to the call for urban planning to follow the 'urban harvest' approach. In this way, cities could adopt principles of industrial ecology (as often practiced in eco-industrial parks) in order to meet their inhabitants' demands for energy, water and waste management, in ways which reduced environmental and economic risks. However, the complexity of a city presents a technical challenge for planners and decision makers; hence the Introduction suggested that the complex network of processes and resources could be considered as a system which can be mathematically formalised, and thus can be subject to mathematical programming in order find the optimal mix of infrastructure which meets urban resource demand. This work is situated within the field of urban metabolism -- an area of study which provides the ideas to consider the relationship between a city and its resources. Using the language of this concept, the challenge of this thesis is to offer insights on how cities could move from linear to circular metabolisms. This introduction led to to the following research question:

> *By how much can an area's metabolism be quantifiably improved by an optimisation model which integrates the planning of energy, water and waste systems?*

This question was broken down into three aims, the first of which was to *"Investigate the opportunity and methodology"*. Chapter 2 began this by conducting systematic literature reviews to explore how the UM field currently understands issues of urban resource management, and the ways in which optimisation modelling has been applied to urban resource management. This review gave rise to two research voids to be filled:

- First, there was a need to consider an area's metabolism as emerging from an *engineered-system*. This novel conceptualisation seeks to understand a city's aggregate metabolic flows as a function of the network of processes that manage energy, water and waste within a city.
- Second, there was a need to go beyond current approaches to urban resource optimisation, in which resources were generally siloed according to their type (i.e. energy, water, or waste). Instead, models are needed which would consider the optimisation of urban resources in a *highly integrated* manner. These models would simultaneously optimise the design of energy, water and waste systems.

This conceptualisation of the city as an engineered system would subsequently facilitate the formulation of a mathematical model which could optimise the mix of urban resource management processes in order that energy, water and waste systems could be considered in a highly integrated manner.

With a new conceptual model proposed, Chapter 3 showed how metabolism could be quantified by different metrics and Chapter 4 assembled a publicly-available dataset of energy, water and waste management processes. The content of both these chapters would subsequently to be useful in the modelling: the former gave methods which could quantify the extent to which the model could improve an area's metabolism; the latter would provide data for use in the model.

With the groundwork laid, the second aim was to *"Develop a model which computes the optimal mix of resources to meet demand for goods and services"*. To that end, Chapter 5 extended an existing formulation for an urban energy systems model, to incorporate energy, water and waste resources and processes. A particular requirement of the model was *generality*, so that the model could handle multiple resource types in a user-friendly and tractable way. Of three test formulations, the PRaQ method most suited these priorities, though the formulation has been made public with a benchmarking study to facilitate future improvements of the formulation.

The third aim was to *"Assess how well the models improve urban metabolism"*. This was addressed in Chapter 6 by applying the PRaQ model to the ShannGu Power Company case study -- an urban development in China. This demonstrated that a city's metabolism was indeed governed by the engineered-systems at work in an area, by showing that optimal process mixes and patterns of aggregate metabolic flows varied according to different design objectives and process availability.

## Research contributions

\begin{sidewaystable}[]
\footnotesize
\centering
\caption{Summary of how this thesis answers the call for systems integration.}
\label{tab:summary-contributions-furtherWork}
\begin{tabular}{llp{6cm}p{8cm}}
\toprule
Chapter & Thesis aim & Contribution to field                                                                                                                                                                                & Further work                                                                                                                                                                                                                                                                                                                          \\
\midrule
2       & 1          & Conceptual model                                                                                                                                                                                     &                                                                                                                                                                                                                                                                                                                                       \\
3       & 1          & Assessed the ability of various ways to evaluate the efficiency of multi-resource systems (such as cities), to provide metrics which can be used to quantify the efficiency of an area's metabolism. & From Section \ref{sec:metrics-conclusions}: Confirm our conclusions regarding metrics with other UM datasets; perform grey-box analysis at a higher resolution, to quantify the trade-off between insights obtained and data required to obtain them; explore additional metrics; and apply this analysis to other types of multi-resource system. \\
4       & 1          & Open-source database providing quantitive information on behaviour of processes which manage energy, water and waste.                                                                                & From Section \ref{sec:database-conclusions}: Continuous improvement of the database (new processes, more information such as process costs, extend to other processes important to metabolism such as steel manufacture); developing the eco-system in which the database lives, so it can link to other opensource UM data.                        \\
5       & 2          & The PRaQ model formulation and benchmarking study which can be used to help further develop the formulation                                                                                          & From Section \ref{sec:model-dev-conclusion}: Continuous improvement of formulation and solutions, including piecewise linear and nonlinear formulations (requiring nonlinear models of the database processes), and heuristic-based solution methods such as genetic algorithms.                                                                    \\
6       & 3          & Demonstration that model can quantifiably improve UM                                                                                                                                                 & From Section \ref{sec:case-study-further-work}: improve input data accuracy (e.g. demands); apply model at an operational level; investigate other objectives; further sensitivity analysis                                                                                                                                                             \\
\bottomrule
\end{tabular}
\end{sidewaystable}

This thesis aimed to respond to calls for cities to become more sustainable through via circular (rather than linear) metabolisms; this is to be achieved by using the wastes of one sector as the inputs to another, or -- in the language of this thesis -- developing highly integrated urban energy, water and waste systems. The novel contributions of this thesis are summarised in Table \ref{tab:summary-contributions-furtherWork} and are presented with more detail below:

1. *Two smaller contributions.* Before considering the four main contributions of this thesis, it is worth mentioning two smaller contributions, which can be considered as 'by-products' of this research. The first is the review of the literature which comprises the urban metabolism research landscape, encompassing the origins and purposes of UM studies, the way UM is conceptualised, the methods UM studies employ, and the models used to understand how components of UM systems relate to one another. The second smaller contribution is the method of systematic literature review used to gather content for Chapter 4's database: this method included filtering research according to quality, identifying relevant articles, and categorising articles according to resource type. These search and organisation methods might find useful application in urban metabolism and other fields.

2. *A new conceptual model of urban metabolism.* Since a city's metabolism was first conceptualised by @Wolman1965 as a black-box, others have been extending the idea to increase its explanatory power, for example with @Newmann1999 adding 'liveability' to the idea of resource flows. Other additions were proposed by @Girardet1990, who conceptualised the re-use of a city's outputs as inputs, to show how a city's overall resource throughput could be reduced. @Zhang2009a took the concept beyond the black box, by suggesting that inside it was a network of economic sectors between which resources would move. The main theoretical contribution of this thesis is to extend Zhang's network concept to include the *engineered systems* which convert and transport resources -- this model proposed the terms 'top', 'middle', and 'bottom' of a system to refer to an area's resource-management demands, the network of processes and resource flows which meet those demands, and the resulting aggregate metabolic flows into and out of an area, respectively. \newline
  The power of conceptual models is that they provide the ideas and language to relate components of real-world systems to one another in ways that allow people to think through the effects on a system when one or more of those components change. This thesis contributes a new way to conceptualise how energy, waste and waste management processes in the middle of a system affects the aggregate metabolic flows at the top of a system, as they are driven by demands at the bottom.

3. *The PRaQ model.* The theoretical contribution above then became practical through the thesis' main methodological contribution -- the PRaQ model. This mathematically formalises the conceptual model, so it can be use to perform highly integrated systems optimisation on real-world problems, simultaneously meeting the demands of more than one system. Thus, the field of urban metabolism now has its own optimisation model, something previously only enjoyed by individual sectors and arguably therefore did not do much to optimise metabolism as a whole. As such, this work adds another voice to the discussion on urban sustainability, by providing a tool which helps planners and policy makers take calls for systems integration from idea to reality.

4. *Guidance on how best to measure the efficiency of an area's metabolism.* To achieve efficient urban metabolisms by integrating multiple systems raises the question of how system performance should be measured. In an energy system, this is fairly straightforward because there is just one resource type, but integrated urban systems manage multiple resource types. Chapter 3 classified a city as a multi-resource system which therefore exhibited the multi-resource trade-off problem, which could be measured by black-box methods (such as water footprint and energy efficiency) or grey-box box methods (surch as exergy analysis and ecological network analysis). This work found that the question of how well sectors work together is best answered by grey-box analysis. ENA also relates this contribution to @Zhang2009's work in that the engineered system's processes modelled by PRaQ each belong an economic sector, and so ENA highlights economic and management implications of integrated systems. This contribution helps decision makers determine which metrics they should use when adopting intersectoral synergies in urban planning. 

5. *The open source database of resource conversion processes.* This final contribution adds to the growing collection of open source tools for industrial ecology. Each record in the database uses YAML data to store information about the relative quantities or a process' inputs and outputs, which can be used in PRaQ modelling.

In summary, the PRaQ model shows that the process-oriented perspective of UM is a fruitful avenue of research, which can now enable the (as yet unexplored) possibility of optimisation modelling. Moreover, the *way* this thesis makes these contributions is designed to encourage research into this area. This thesis encourages use of PRaQ to continue, in particular through the growing community and opensource ecosystem within UM and IE [@Davis2010]. First, the opensource database of resource management processes for others to use in their own work. This database can be extended and edited by others, meaning the possibilities to study urban metabolism from a process-oriented perspective encouraged by this thesis' conceptual model can continue to grow. Second, publishing PRaQ's formulation with a benchmarking problem encourages future development of the model formulation.

Moreover, these open-sourced contributions can be taken up for other uses, outside PRaQ modelling. Opensource content forms something akin to an 'ecosystem', rather than a static set of tools and datasets. This means that uses of the benchmarking problem and database are not limited to those discussed here, but can be used in other work. These contributions mean the field of UM is better placed to answer questions about how cities can improve their metabolism through systems integration: planners, policymakers and decision makers now have the means to think about UM as a whole, rather than individual sectors as a part, in an objective and user-friendly way.

<!--
The idea of highly integrated urban resource management systems did raise questions about how the performance of multi-resource systems should be best quantified. Chapter 4's answer to this provides another theoretical contribution to advocate for grey-box metrics to understand what's going on inside a UM system. 

Turning to consider some specific ways this research may inform the future development of urban areas, the SPC case study offers a very early view of the way UM systems may develop in the future, as UM continues to become part of the sustainability discussion, and is therefore evermore incorporated into urban design [TODO: link to Kennedy's paper, and that blogpost]. The model opens up several avenues of exploration:

- the use of systems with more process types (particularly of a smaller capacity), in decentralised networks, rather than the more traditional centralised systems. Decentralisation is already happening within individual sectors (e.g. energy supply and water supply), so the SPC modelling results suggest that this can be coupled with advances in intersectoral synergies, with waste- and by-products cascading through a system [TODO: provide reference].
- The use of wildcard type modelling might inform best what new technologies are particularly worthy of further R&D, in order to fit best into existing systems. Research could.
- Furthermore, a city with a greater variety of processes could well be more flexible in responding to changing demands in resource-efficient ways.

- Hidden savings: don't forget that (unlike energy optimisation models), the water and waste flows for energy processes are considered!
-->

## Shortcomings and further work

<!--
Development of the PRaQ model can be seen as the coming together of four ideas: urban metabolism, industrial ecology, systems optimisation modelling, and open-source development. This thesis has focussed on introducing this collocation of ideas and how they might be applied. However, the focus has been upon introducing the idea, and thus some detail has been sacrificed for the sake of introducing a new idea to UM. Thus the early nature of this work means there is much more value to be squeezed out from the contributions of this thesis towards using PRaQ to improve urban metabolism.
-->

Some specific proposals for further work have been given in the concluding sections of Chapters 3, 4, 5 and 6 and summarised in Table \ref{tab:summary-contributions-furtherWork}. The further work of Chapters 4 and 5 (namely, the extension of the database and the development of PRaQ, are enabled by the open source contributions of this thesis. In time, incremental developments will hopefully lead to a process-oriented UM model and associated database that includes all the features desired by users, representing process behaviour with sufficient accuracy, and is tractable and user friendly. Other proposals for further work are broader, and are considered in the following three subsections.

### The application of PRaQ {#sec:furtherWork-PRaQ-application}

In addition to the suggestions application of PRaQ in Chapter 6, there are a number of other ways PRaQ could be applied:
<!--
One consideration absent thus far is that of model validation, in other words, the question of how closely the model represents reality in practise. For many models, validation is a simple matter of comparing model results to experimental results. However, validation is not so easy for modelling at the urban scale. One possible way to validate PRaQ could be to apply it to existing urban areas for which sufficient information is known.

Not only would the area's demand profile need to be known (as is typical in PRaQ case studies), so would its process mix and layout -- the values of these variables [TODO: list them] would then be fixed, and the model run, to return a schedule of resource flows (both the aggregate metabolic exchanges into and out of the city, and the inter-process flows). It would then be possible to quantify how closely the modelled schedule matches that of real-life. This would be a major piece of work, and the first step would be to assemble the dataset for a real city.
-->

1. *Inform the investment decisions existing cities.* PRaQ could provide guidance as to how an existing city should change its processes, in view of certain constraints (e.g. budget and geography) and particular design objectives (e.g. minimising emissions). In these cases, some of the variables (e.g. to model already existing process which should remain in place) would be fixed, while others are free to change (i.e. to represent the removal, replacement, or addition of new processes). This would require a datasets which provided the demand profiles and behaviour of their existing processes.

2. *Testing resilience to demand shocks .* A city may undergo sudden shocks of unusually high demand for a particular resource. PRaQ could be used to test whether a current mix of processes is able to deliver goods and services under such conditions, by seeing how much a process mix needs to change in order to accommodate the new demand profile, or whether (ideally) the new demands could be met with the same process mix operating to a different schedule.

3. *Application at different time scales.* Other more simple applications of PRaQ could be to investigate urban metabolism at different temporal resolutions. In going to greater granularity, planners can investigate the effect of process *operation* on metabolism. In using larger time intervals (e.g. changin demands at a monthly level over several years, perhaps corresponding to changing populations and demographics), planners can assess the long-term investment decisions which might improve an area's metabolism.

4. *Application at different spacial scales.* Increasing the spatial resolution would enable PRaQ to consider the resource flows into and out of and within buildings. This would require its own database of bulding-level conversion and transport processes (such as sinks, water pipes, lavatories, electric heaters, compost bins etc.). Such modelling could be used to show how buildings can invest to reduce their overall consumption and waste. On the other hand, PRaQ could be scaled up to regional and national levels to optimise the chains of resource conversions which occur over larger parts of an economy. Again, this application would require their own database of processes, perhaps including agriculture, livestock farming, forestry, etc.

5. *Extension beyond energy, water and waste sectors.*. Processes not belonging to the energy, water and waste sectors have not been considered in this thesis. Examples include the manufacture of iron and steel (which Chapter 3 showed was important in a city such as Sao Paulo). Introducing other sectors would be achieved by extending the database of processes.

### The place of PRaQ within broader considerations

This thesis has been limited to considering the how the process mix in the middle of a system affects aggregate metabolic flows at the top. However, cities do not exist in a vacuum, free from other concerns. Cities are not merely resource-managers. As the Introduction noted, a city's primary value is socioeconomic; this brings with it all sorts of considerations. Therefore future work should consider how PRaQ sits within socioeconomic systems.

Perhaps one reason for the lack of models which optimise integrated urban resource management are the economic and market-imposed limitations. For example, energy, water and waste are typically managed separately, with the system operators each seeking to maximise their own profits. PRaQ could therefore contribute to arguments which favour planned utilities management against leaving resource management to the mercy of liberalised markets. Perhaps PRaQ gives a basis to introduce incentives for various public and private utility companies to work together, helping cities to become more like EIPs in the management of resources. On the other hand, PRaQ-inspired resource management may well face the same sort of push back being received by 'smart cities' -- namely that it could impose a technocratic vision of a city [@Greenfield2013].

Finally, PRaQ can be used in conjunction with other models[^link-type]. For example, there already exist models which optimise process use at a household level (e.g. @Chen2013). These could be used to define household demands at the bottom of the system, which could then be fed into PRaQ, to optimise resource flows at the urban scale. Similarly, demands at the bottom of the system could come from tools which perform 'agent-based modelling'; these derive consumer demands from the activities a population participate in (e.g. shopping, educations, travelling, etc.).

At the top of the system, the aggregate metabolic flows arising from a process mix could be used in regional or national input-output economic models (e.g.@Leontief1951), in order to investigate the larger economic impacts of a system's middle. In a similar vein, aggregate flows could be fed into environmental models, such as those which quantify local emissions or hydrological conditions -- in this way, modellers can investigate the environmental impacts of a system's middle.

[^link-type]: Multiple models can either be soft-linked or hard-linked. In soft-linking, the models are run independently, with the results of one being manually fed to become the parameters of another. In hard-linked models, this transfer of one model's outputs to the others inputs is automated using code.

### The development of the UM open source ecosystem {#sec:further-work-community}

The further work in Table \ref{tab:summary-contributions-furtherWork}, and the above two sections made several mentions the opensource contributions of this work, and possible ways this work can be extended, with the main examples being extensions to the database and development of the model. However, as pointed out earlier, open source content often lives in an 'ecosystem'. This means the potential of PRaQ is realised not just by the developments to the model itself, but also by the presence of *other* open source content. If some of the suggestions above are to be realised, then this might depend on this other content become available.

One example would be if PRaQ was to be applied to existing cities \ref{sec:furtherWork-PRaQ-application}. This could be facilitated via an open source dataset of exisiting city demand profiles, and a database of the processes they use (recording the same type of information as the current database), and their geography. This is a substantial project, and perhaps only the open source community is up to such a task. Should it be achieved however, it would be a huge step forward for realising PRaQ's purposes in the real world.

Finally, the current proposals in this thesis are not yet fully open source, because the compiler for the GAMS language (in which PRaQ is encoded) is proprietary. There do however exist examples of successful optimisation models written in open source programming languages, for example, the Calliope energy systems model written in Python. The online repository of code and documentation makes an excellent example of what PRaQ could become[^callope].

[^callope]: \url{http://calliope.readthedocs.io/en/stable/}

<!--
The simplest opensource development is to extend the @Ravalde2016, as this merely involves adding and editing the YAML files -- something that requires virtually no specialist knowledge, and nothing more than a text editor. However, the gains here are potentially large. Additions to the current processes include process costs (appropriate to specific locations, currencies, exchange rates, and purchasing power parities), spatial footprints, process type (i.e. domestic, commercial, municipal, or industrial). Other processes can be added, even outside the current types considered, for example to include industrial processes such as steel and cement manufacturing, and chemical production. Finally, all of the above, can be incorporated into the semantic web ecosystem (as outlined in Chapter 4), where database content links to structured and unstructured information, regarding the top, middle, and bottom of UM systems.
-->

## PRaQ: Onwards and upwards...

This thesis began with the premise that cities are vital, providing invaluable socioeconomic benefits to humanity, but at the same time, presenting significant environmental and economic challenges related to resource management. Cities, by their very nature, are well-placed to address some of these challenges because the co-location of processes in them can enable synergies between energy, water and waste management systems. This work has brought together ideas and methods from urban metabolism, industrial ecology, optimisation modelling, and the open source community, to advance the theory of urban metabolism and develop a model which considers how *Highly integrated urban energy, water and waste resources* might harness intersectoral synergies which mean urban resource demand can be met in more environmentally and sustainable ways.

Models advance understanding of a system by explicitly representing that system in a way that can be communicated and challenged -- an insight powerfully expressed by Professor Joshua Epstein which opens this chapter. The PRaQ model seeks to do that for one particular aspect of cities, namely integrated resource management. There is of course still someway to go, and to that end the developments suggested above (as well as developments others will offer) will further advance the place of modelling solutions to how energy, water and waste sectors might work better together.

In an increasingly resource-constrained world which faces the challenges of population growth, global warming, water scarcity, shrinking landfill capacity, economic stagnation, and other challenges, cities are being hailed as the most efficient means to provide goods and services to an ever-increasing global population. It is imperative that reasoned-out approaches are used to help the world become more economically and environmentally sustainable. This thesis introduces a PRaQtical way forward.
