# Abstract {.unnumbered}

Urbanisation continues to bring socioeconomic well-being to an ever-growing global urban population. Nevertheless, there is an environmental and economic imperative for cities to use resources more sustainably. One way to achieve this is to take advantage of the fact that, in cities, resource management infrastructure from the energy, water and waste sectors is co-located, such that the wastes and by-products from one process can become the inputs to another (for example, sending organic waste to anaerobic digestion to produce biogas for energy generation). This thesis provides planners and policy makers with means to begin realising these intersectoral synergies, through contributions to the field of urban metabolism. First, methods are needed which quantify how well different sectors work together to make an area’s metabolism more efficient; to that end, analysis on historic urban resource flows show the usefulness of exergy analysis and ecological network analysis. Second, data is required which shows the possibilities for one process’s wastes to become another’s inputs; for this, a database is assembled which records the resource consumption and production of 202 types of urban resource management process, and made publicly available. Third, the Processes, Resource and Qualities (PRaQ) model is developed; PRaQ is a mixed-integer linear programme which simultaneously chooses the mix of energy, water and waste management processes an area could use to minimise an objective (emissions, for example), thereby taking into account intersectoral synergies. The formulation is made available as a benchmarking study to facilitate future development of the model. Applying PRaQ to a new urban development in China shows how an area’s urban metabolism can be made measurably more efficient according to various metrics. In summary, this work advances the urban metabolism concept for its application to improving urban resource sustainability, by showing how a city’s mix of process affects its overall metabolic flows.

<!--
Urbanisation has and will continue to bring socioeconomic well-being to an ever-growing global urban population, but they need to use resource more sustainably. One way to do this, is to take advantage of the fact that in cities, resource management infrastructure from the energy, water and waste sectors is co-located, such that the wastes and by-produces of one process can become the inputs to another.

To help planners and policy makers realise these benefits, this thesis introduces a mixed-integer linear programme which can choose the optimal mix of energy, water and waste management processes simultaneously, thereby taking into account the synergies and interactions between these sectors.

Formulating this model advances understanding of the urban metabolism concept, by showing how a city's mix of process affects its overall metabolic flows. Application of the model shows how it is possible to improve an area's metabolism, as measured by appropriate metrics. In summary, it is recommended that process-oriented approaches to urban sustainability should be considered in view of urban challenges.
-->

<!--
In practice, planning a city's mix of processes and schedule of resource imports, exports, and inter-process transfers is nontrivial due to the many permutations and combinations involved, but formalising a city's network of resource management infrastructure as a system enables optimisation modelling

So that planners and policy makers can take advantage of optimisation modelling, this thesis introduces a usable and tractable optimisation mode which can choose the optimal mix of processes a city should use to manage its resources according to a given objective (such as minimising emissions). 

from a theoretical UM perspective
or an optimisation modelling approach

This thesis asks the question,
and answers with a model, whose results demonstrate that
-->
