#!/bin/bash

## Default procedure
ssh tr608@ps-lfe01.ps.ic.ac.uk rm -rf "~/ShannGu"

rsync -ru model tr608@ps-lfe01.ps.ic.ac.uk:~/ShannGu

scp  batch-process tr608@ps-lfe01.ps.ic.ac.uk:~/ShannGu/model
scp gams_time.sh tr608@ps-lfe01.ps.ic.ac.uk:~/ShannGu/model
scp pu.sh tr608@ps-lfe01.ps.ic.ac.uk:~/ShannGu/model

